[workspace]
members = [
    "core",
    "server",
    "web",
]
exclude = ["plugins/*", "components/*"]
resolver = "3"

[workspace.package]
authors = ["Uriah Galang <codeitlikemiley@gmail.com>"]
keywords = [
    "accounting",
    "bookeeping",
    "tax",
    "plugin",
    "wasm",
]
license = "MIT"
repository = "https://github.com/codeitlikemiley/topg/"
edition = "2024"
rust-version = "1.88.0"

[workspace.dependencies]
anyhow = "1"
async-trait = "0.1"
axum = "0.8.4"
crossbeam-channel = "0.5"
facet = "0.28.0"
futures = "0.3"
futures-util = "0.3"
js-sys = "0.3"
log = "0.4"
pretty_env_logger = "0.5"
regex = "1.11"
rust_decimal_macros = "1.36"
serde = "1"
serde_json = "1"
tracing = "0.1"
url = "2.5"
wasm-bindgen = "0.2"
wasmtime = "27.0"
wit-bindgen = "0.45.0"

[workspace.dependencies.chrono]
version = "0.4"
features = ["serde"]

[workspace.dependencies.crux_core]
git = "https://github.com/redbadger/crux"
rev = "f0d7d010b9c7c44d6e75e024719c87ab85275972"
features = ["facet_typegen"]

[workspace.dependencies.crux_http]
git = "https://github.com/redbadger/crux"
rev = "f0d7d010b9c7c44d6e75e024719c87ab85275972"
features = ["facet_typegen"]

[workspace.dependencies.insta]
version = "1.43"
features = ["yaml"]

[workspace.dependencies.leptos]
version = "0.8"
features = ["csr"]

[workspace.dependencies.leptos_router]
version = "0.8"

[workspace.dependencies.rand]
version = "0.9"
features = ["os_rng"]

[workspace.dependencies.reqwest]
version = "0.12"
features = [
    "stream",
    "json",
]

[workspace.dependencies.rust_decimal]
version = "1.36"
features = ["serde"]

[workspace.dependencies.tokio]
version = "1"
features = ["full"]

[workspace.dependencies.tracing-subscriber]
version = "0.3"
features = ["env-filter"]

[workspace.dependencies.uuid]
version = "1"
features = [
    "v4",
    "v5",
    "serde",
]

[workspace.dependencies.sqlx]
version = "0.8"
features = [
    "runtime-tokio-native-tls",
    "sqlite",
    "migrate",
    "chrono",
    "uuid",
]
