[package]
name = "taxtalk_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chrono = { workspace = true , features = ["serde"] }
futures.workspace = true
regex.workspace = true
rust_decimal.workspace = true
rust_decimal_macros.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
url.workspace = true
uuid.workspace = true
wasmtime = { workspace = true, features = ["component-model"] }
log = { workspace = true, optional = true }
pretty_env_logger = { workspace = true, optional = true }
tempfile = "3.8"
sqlx = { workspace = true }
fuzzy-matcher = "0.3"

[dev-dependencies]
insta.workspace = true

[[bin]]
name = "plugin_codegen"
path = "src/bin/plugin_codegen.rs"

[features]
default = []