[package]
name = "command-palette"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
leptos = { workspace = true }
leptos_meta = { workspace = true }
leptos_router = { workspace = true }
console_error_panic_hook = { workspace = true }
wasm-bindgen = { workspace = true }
web-sys = { workspace = true, features = ["HtmlElement", "KeyboardEvent", "EventTarget"] }
serde = { workspace = true }
serde_json = { workspace = true }
gloo-timers = { workspace = true }
gloo-storage = "0.3.0"
fuzzy-matcher = "0.3.7"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-test = { workspace = true }

[dev-dependencies]
wasm-bindgen-test = { workspace = true }